# Information
autor: Matheus Castiglioni
baseurl: ""
description: "Documentação do projeto MDown"
email: matheushcastiglioni@gmail.com
projectname: mdown
projecturl: https://github.com/mahenrique94/mdown
title: "MDown"
url: mdown.matheuscastiglioni.com.br

# Configuration
collections:
  pages:
    output: true
    permalink: /:name
css: lib/mdown.css
layout: "page"
js: lib/mdown.js
static_files: "assets/"